services:
  - type: web
    name: people-team-dashboard-metabase
    env: docker
    image: docker.io/metabase/metabase:latest
    plan: free
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: postgres
      - key: MB_DB_PORT
        value: 5432
      - key: MB_DB_USER
        value: postgres
      - key: MB_DB_PASS
        sync: false   # You will set this in Render's dashboard for security
      - key: MB_DB_HOST
        value: db.ikojzddhsvvquwnkoxda.supabase.co
      - key: MB_ENCRYPTION_SECRET
        generateValue: true  # Random secret generated on deploy
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
