services:
  - type: web
    name: metabase
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ""
    image:
      url: docker.io/metabase/metabase:latest
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: metabase
      - key: MB_DB_PORT
        value: "5432"
      - key: MB_DB_USER
        fromService:
          name: metabase-db
          type: postgresql
          property: user
      - key: MB_DB_PASS
        fromService:
          name: metabase-db
          type: postgresql
          property: password
      - key: MB_DB_HOST
        fromService:
          name: metabase-db
          type: postgresql
          property: host

databases:
  - name: metabase-db
    databaseName: metabase
    plan: free
    ipAllowList: []
