services:
  - type: web
    name: metabase
    env: docker
    plan: free # You can switch to 'starter' or higher if you need more resources
    dockerfilePath: Dockerfile
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_CONNECTION_URI
        fromSecret: SUPABASE_DATABASE_URL
      - key: MB_SITE_URL
        value: https://metabase.onrender.com # Replace with your Render URL
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx512m"

databases: []
